export {
    authUserLogin,
    authAdminLogin,
    authAdminVerify,
    resendCode,
    authLogout,
    setAuthRedirectPath,
    setHash,
    authCheckState,
} from './auth';

export {
    getContent,
    setLanguage,
} from './content';

export {
    resetAdmins,
    getAdmins,
    getAdmin,
    postAdmins,
    patchAdmins,
    deleteAdmins,

    resetCanal,
    getFormulae,
    getFormula,
    postFormulae,
    patchFormulae,
    deleteFormulae,
    getSubscriptions,
    getSubscription,
    getSubscriptionsInfo,
    postSubscriptions,
    patchSubscriptions,
    deleteSubscriptions,

    resetCities,
    getCities,
    getCity,
    postCities,
    patchCities,
    deleteCities,

    resetCms,
    getCms,
    postCms,
    patchCms,
    deleteCms,

    resetCustomers,
    getCustomers,
    getCustomer,
    getCustomersInfo,
    postCustomers,
    patchCustomers,
    deleteCustomers,

    resetDashboard,
    getDashboard,

    resetExpenses,
    getExpenses,
    getExpense,
    getExpensesInfo,
    postExpenses,
    patchExpenses,
    deleteExpenses,

    resetFeatures,
    getFeatures,
    getFeature,
    postFeatures,
    patchFeatures,
    deleteFeatures,

    resetLanguages,
    getLanguages,
    getLanguage,
    postLanguages,
    patchLanguages,
    deleteLanguages,

    resetMethods,
    getMethods,
    getMethod,
    postMethods,
    patchMethods,
    deleteMethods,

    resetQuarters,
    getQuarters,
    getQuarter,
    getQuartersInfo,
    postQuarters,
    patchQuarters,
    deleteQuarters,

    resetRoles,
    getRoles,
    getRole,
    getRolesInfo,
    postRoles,
    patchRoles,
    deleteRoles,

    resetUsers,
    getUsers,
    getUser,
    getUsersInfo,
    postUsers,
    patchUsers,
    deleteUsers,
} from './backend';